### ISSUE TITLE
There are 2 traineddata for khmer language

### ISSUE THREAD

**Issue by phyrumsk** [tesseract-ocr/tessdata_best#6]
I cloned tessdata_best and found 2 traineddata files for Khmer language, khm.traineddata (size=8.1MB) and Khmer.traineddata (size=12MB). So I wonder which one is the right file for khmer language?

Thanks with Best regards,
Phyrum

**Comment by Shreeshrii** [comment]
khm is for Khmer,
Khmer is for Khmer script and has English in it too.

Please try both and report your feedback. Sometimes script traineddata
gives better results.

For faster output, look at tessdata_fast

On 27-Sep-2017 8:49 AM, "phyrumsk" <notifications@github.com> wrote:

I cloned tessdata_best and found 2 traineddata files for Khmer language,
khm.traineddata (size=8.1MB) and Khmer.traineddata (size=12MB). So I wonder
which one is the right file for khmer language?

Thanks with Best regards,
Phyrum

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tessdata_best/issues/6>, or mute the
thread

**Comment by phyrumsk** [comment]
Thanks I'll try.

**Comment by amitdo** [comment]
@zdenop, please close this issue.

**Comment by amitdo** [comment]
Khmer OCR fine tune engine for Unicode and legacy fonts using
Tesseract 4.0 with Deep Neural Network

http://ona2017.khmernlp.org/wp-content/uploads/paper/papers/paper/ONA_2017_paper_Khmer_OCR_FineTune_Engine.pdf

The OP is one of the authors of this paper.
